services:
  - type: web
    name: my-laravel-project
    env: php
    plan: free
    buildCommand: "composer install && php artisan key:generate && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
